# Generated by Django 4.2.6 on 2023-10-15 01:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_en', models.CharField(max_length=250)),
                ('question_text_ru', models.CharField(max_length=250)),
                ('answer_text_en', ckeditor.fields.RichTextField()),
                ('answer_text_ru', ckeditor.fields.RichTextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
            ],
            options={
                'verbose_name': 'Question',
            },
        ),
    ]
